const imageMapping = {
    "../assets/image.png": require("../assets/image.png"),
    "../assets/image6.png": require("../assets/image6.png"),
    "../assets/ic-message.png": require("../assets/ic-message.png"),
    "../assets/OIP.png": require("../assets/OIP.png"),
    "../assets/image00.png": require("../assets/image00.png"),
    "../assets/ic-phone.png": require("../assets/ic-phone.png"),
    "../assets/ic-bookmark.png": require("../assets/ic-bookmark.png"),
    "../assets/logo12.png": require("../assets/logo12.png"),
    "../assets/face1.png": require("../assets/face1.png"),
    "../assets/face2.png": require("../assets/face2.png"),
    "../assets/face3.png": require("../assets/face3.png"),
    "../assets/face4.png": require("../assets/face4.png"),
    "../assets/face5.png": require("../assets/face5.png"),
    "../assets/face6.png": require("../assets/face6.png"),
    "../assets/main-logo.png": require("../assets/main-logo.png"),
    "notificationsIcon": require("../assets/logo1.png"),
    "homeLogo": require("../assets/logo11.png"),
    "bedIcon" : require("../assets/logo5.png"), 
    "bathIcon" : require("../assets/logo6.png"),
    "backIcon" : require("../assets/logo7.png"),
    "bookmarkIcon" : require("../assets/logo8.png"),
    "phoneIcon" : require("../assets/logo9.png"),
    "messageIcon" : require("../assets/logo10.png"),
    //Antelias Property 
    "../assets/images/outdoor.jpg" : require("../assets/images/outdoor.jpg"),
    "../assets/images/outdoor-1.jpg" : require("../assets/images/outdoor-1.jpg"),
    "../assets/images/outdoor-2.jpg" : require("../assets/images/outdoor-2.jpg"),
    "../assets/images/outdoor-3.jpg" : require("../assets/images/outdoor-3.jpg"),
    "../assets/images/indoor.jpg" : require("../assets/images/indoor.jpg"),
    "../assets/images/indoor-1.jpg" : require("../assets/images/indoor-1.jpg"),
    "../assets/images/indoor-2.jpg" : require("../assets/images/indoor-2.jpg"),
    "../assets/images/indoor-3.jpg" : require("../assets/images/indoor-3.jpg"),
    "../assets/images/indoor-4.jpg" : require("../assets/images/indoor-4.jpg"),
    "../assets/images/indoor-5.jpg" :  require("../assets/images/indoor-5.jpg"),
    "../assets/images/bathroom.jpg" : require("../assets/images/bathroom.jpg"),
    "../assets/images/bathroom-1.jpg" : require("../assets/images/bathroom-1.jpg"),
    "../assets/images/bathroom-2.jpg" : require("../assets/images/bathroom-2.jpg"),
    "../assets/images/hall.jpg" : require("../assets/images/hall.jpg"),
    "../assets/images/hall-1.jpg" : require("../assets/images/hall-1.jpg"),
    "../assets/images/building.jpg" : require("../assets/images/building.jpg"),
}

export default imageMapping;